[package]
org = "zeio"
name = "search"
version = "0.1.0"
distribution = "2201.3.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "zeio"
name = "index"
version = "0.3.0"
repository = "local"
